from django.urls import path
from .views import (
    BookDetailAPIView,
    BookListAPIView,
    CategoryListAPIView,
    ThemeView,
    ThemeListView,
    SelectedThemeView,
    GalleryImageUploadView,
    UpdateSliderOrderView,
    SliderListView,
    SliderDetailView,
    ImageListView,
    UserProfileView,
    CreateOrderView,
    UserOrdersView,
    OrderDetailView,
    UpdateOrderStatusView,
    add_image_to_slider,
    user_status,
)

urlpatterns = [
    path("user_status/", user_status, name="user_status"),
    path("profile/", UserProfileView.as_view(), name="user_profile"),
    path("books/", BookListAPIView.as_view(), name="book-list"),
    path("books/<int:pk>/", BookDetailAPIView.as_view(), name="book-detail"),
    path("categories/", CategoryListAPIView.as_view(), name="category-list"),
    path("theme/default/", ThemeView.as_view(), name="theme"),
    path("themes/", ThemeListView.as_view(), name="theme-list"),
    path("themes/select/", SelectedThemeView.as_view(), name="select-theme"),
    path("upload/", GalleryImageUploadView.as_view(), name="gallery_image_upload"),
    path("images/", ImageListView.as_view(), name="image-list"),
    path(
        "update-slider-order/",
        UpdateSliderOrderView.as_view(),
        name="update_slider_order",
    ),
    path("sliders/", SliderListView.as_view(), name="slider-list"),
    path("sliders/<int:slider_id>/", SliderDetailView.as_view(), name="slider-detail"),
    path("sliders/<int:slider_id>/add_image/", add_image_to_slider),
    path("orders/", CreateOrderView.as_view(), name="create_order"),
    path("orders/user/", UserOrdersView.as_view(), name="user_orders"),
    path("orders/<int:order_id>/", OrderDetailView.as_view(), name="order-detail"),
    path(
        "orders/<int:pk>/update-status/",
        UpdateOrderStatusView.as_view(),
        name="update_order_status",
    ),
]
