# Generated by Django 4.2.17 on 2025-01-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
    ]
