# Generated by Django 4.2.17 on 2025-01-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='approved',
            field=models.BooleanField(null=True),
        ),
    ]
