# Generated by Django 4.2.17 on 2025-01-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_galleryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='image',
            new_name='path',
        ),
    ]
