# Generated by Django 4.2.17 on 2025-01-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_image_galleryimage_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={},
        ),
        migrations.RenameField(
            model_name='galleryimage',
            old_name='path',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='gallery_id',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='slider_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
