# Generated by Django 4.2.17 on 2025-01-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_galleryimage_slider_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='description',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='name',
        ),
    ]
