# Generated by Django 4.2.17 on 2025-01-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_slider_description_remove_slider_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='created_at',
        ),
        migrations.AddField(
            model_name='slider',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='sliders', to='books.galleryimage'),
        ),
    ]
