# Generated by Django 4.2.17 on 2025-01-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_order_city_order_phone_number_order_postal_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
