# Generated by Django 4.2.17 on 2025-01-17 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0028_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='moderators',
            field=models.ManyToManyField(related_name='moderated_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
