# Generated by Django 4.2.17 on 2025-01-17 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0031_alter_category_moderators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='moderators',
            field=models.ManyToManyField(blank=True, limit_choices_to={'userprofile__is_moderator': True}, related_name='moderated_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
