# Generated by Django 4.2.17 on 2025-01-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0032_alter_category_moderators'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModeratorCategory',
        ),
    ]
